//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udi.ecommerceCar.Data.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentaServicio
    {
        public int DetalleVentaServicioID { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> ServicioID { get; set; }
        public Nullable<int> VentaID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> VentaServicioID { get; set; }
    
        public virtual Servicios Servicios { get; set; }
        public virtual VentaServicio VentaServicio { get; set; }
    }
}
