//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udi.ecommerceCar.Data.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentaVehiculo
    {
        public int DetalleVentaVehiculo1 { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<int> VentaVehiculoID { get; set; }
        public Nullable<int> InventarioVehiculoID { get; set; }
        public Nullable<int> VentaVehiculo { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual VentaVehiculo VentaVehiculo1 { get; set; }
    }
}
